[versions]
agp = "8.7.3"
kotlin = "2.0.0"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
appcompat = "1.7.0"
material = "1.10.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
constraintlayoutCompose = "1.0.1"
google-api-client = "1.34.0"
google-http-client = "1.41.1"
google-auth = "1.18.0"
google-sheets = "v4-rev610-1.25.0"
okhttp = "4.11.0"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
google-api-client-gson = { group = "com.google.api-client", name = "google-api-client-gson", version.ref = "google-api-client" }
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version.ref = "google-api-client" }
google-http-client-android = { group = "com.google.http-client", name = "google-http-client-android", version.ref = "google-http-client" }
google-auth-oauth2 = { group = "com.google.auth", name = "google-auth-library-oauth2-http", version.ref = "google-auth" }
google-sheets = { group = "com.google.apis", name = "google-api-services-sheets", version.ref = "google-sheets" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

